### ISSUE TITLE
CSV2DS issue

### ISSUE THREAD

**Issue by gusfryk01** [sasutils/macros#3]
This is a very useful macro. 

There is a situation where the macro does not seem to work, when there are many (>=10 it seems) variables with long names with the first several characters in the names identical. 
This results in the same name being given to 2 of the variables in the generated datastep. The length statement contains the same name twice, once with a numeric and once with a character length. 
I have tried to use the macro with many CSV-files and 6 of them cause this error and they all have variable names as described above.

**Comment by sasutils** [comment]
Did you try to find a solution?  You could use the option OVERRIDES parameter to assign your own names to those columns.

**Comment by sasutils** [comment]
Try it now.  
![image](https://github.com/sasutils/macros/assets/20906808/7fc02752-5ec7-4185-a039-fc0842afd008)

Test code:

```
filename csv temp;
data _null_;
  file csv dsd ;
  length name $50 ;
  do copy=1 to 15 ;
    name=catx('_',repeat('X',39),copy);
    put name @;
  end;
  put;
  do copy=1 to 15;
    put copy @;
  end;
run;

%csv2ds(csv,replace=1)
```

**Comment by gusfryk01** [comment]
That solved it.
